version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/vite-demo'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: 'development'

  - package-ecosystem: 'pip'
    directory: '/python-demo'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10

  - package-ecosystem: 'gomod'
    directory: '/go-demo'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10

  - package-ecosystem: 'cargo'
    directory: '/rust-demo'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
