name: version-checker Coverage

on:
  push:
    branches:
      - main
    paths:
      - "version-checker/**"
      - ".github/workflows/version-checker-coverage.yml"
  pull_request:
    paths:
      - "version-checker/**"
      - ".github/workflows/version-checker-coverage.yml"

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: version-checker
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Run tests with coverage
        run: uv run pytest --cov=version_checker --cov-report=term-missing

      - name: Read custom coverage comment template
        id: coverage_comment_template
        working-directory: .
        run: |
          {
            echo 'content<<COVERAGE_TEMPLATE_EOF'
            cat .github/coverage-comment-template.md.j2
            echo 'COVERAGE_TEMPLATE_EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          SUBPROJECT_ID: version-checker
          COVERAGE_PATH: version-checker
          COMMENT_TEMPLATE: ${{ steps.coverage_comment_template.outputs.content }}

      - name: Store Pull Request comment to be posted later
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action-version-checker
          path: version-checker/python-coverage-comment-action*.txt
